export const projectsData = [
  {
    id: 1,
    name: "Tenis Fresonas",
    miniDescription:
      "A modern shoe store e-commerce and inventory management app",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/EDIT.png?updatedAt=1773153527586",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/DELETE.png?updatedAt=1773153527625",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/CREATE.png?updatedAt=1773153527634",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/DETAIL.png?updatedAt=1773153527406",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/LIST.png?updatedAt=1773153527372",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/HOME.png?updatedAt=1773153527257",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Tenis%20Fresonas/LOGO.png?updatedAt=1773153527291",
    ],
    gitHuburl: "https://github.com/agueroda2004/tenis-fresonas.git",
    liveSite: "https://tenis-fresonas.vercel.app/",
    available: true,
    projectOverview: [
      "Tenis Fresonas is a specialized e-commerce and inventory management solution developed for a digital footwear retailer to bridge the gap between social media sales and a professional storefront. The platform provides a centralized system to showcase products and manage stock in real-time through a high-end, visual catalog experience optimized for the modern market.",
      "The technical architecture features a robust cloud-based infrastructure for persistent data and image storage, complemented by a secure authentication system. I implemented advanced responsive logic to adapt the interface based on device dimensions, alongside full CRUD capabilities, dynamic search by name, and multi-criteria filtering to ensure a seamless user journey.",
    ],
    rolesResponsibilities: [
      "Full-stack Architecture",
      "Authentication System",
      "Cloud Asset Management",
      "Dynamic Search Logic",
      "Responsive UI Design",
    ],
    previusProject: {
      id: 10,
      name: "Taku-Dev",
    },
    nextProject: {
      id: 2,
      name: "Librarian",
    },
    technologies: [
      "React",
      "Tailwind",
      "Supabase",
      "TypeScript",
      "VS Code",
      "Git",
    ],
  },
  {
    id: 2,
    name: "Librarian",
    miniDescription: "A personal digital library and reading tracker",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/LIST.png?updatedAt=1773153653443",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/FINISH.png?updatedAt=1773153653330",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/CREATE.png?updatedAt=1773153653236",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/DELETE.png?updatedAt=1773153653295",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/START.png?updatedAt=1773153653163",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/FAVORITE.png?updatedAt=1773153653460",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/DETAIL.png?updatedAt=1773153653196",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/LOGIN.png?updatedAt=1773153652868",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Librarian/SIGNUP.png?updatedAt=1773153652610",
    ],
    gitHuburl: "https://github.com/agueroda2004/librarian.git",
    liveSite: "https://librarian-daniel-aguero.vercel.app/",
    available: true,
    projectOverview: [
      "Librarian is a personal digital library architected to help users systematically organize their reading habits by categorizing books into custom states such as currently reading, completed, or unread. The platform serves as a comprehensive reading companion, allowing users to transition from simple book tracking to a deep, reflective reading experience through a centralized and intuitive dashboard.",
      "The application features a robust authentication system and full CRUD capabilities, enabling users to manage their collection, re-read titles, and add detailed personal notes to each entry. I integrated a dynamic rating and favorites system to highlight top-tier content, ensuring that every user's library feels personalized, secure, and highly organized.",
    ],
    rolesResponsibilities: [
      "State Management",
      "Secure User Authentication",
      "Rating & Favorites System",
      "Database Schema Design",
      "Minimalist UX Design",
    ],
    previusProject: {
      id: 1,
      name: "Tenis Fresonas",
    },
    nextProject: {
      id: 3,
      name: "Portafolio v1",
    },
    technologies: [
      "React",
      "Tailwind",
      "Supabase",
      "TypeScript",
      "VS Code",
      "Git",
    ],
  },
  {
    id: 3,
    name: "Portafolio v1",
    miniDescription:
      "My first professional portfolio showcasing full-stack skills",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/STACK.png?updatedAt=1773153858931",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/HERO.png?updatedAt=1773153859659",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/default-1920x1080(1).png?updatedAt=1773153859594",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/PROJECT_DETAIL.png?updatedAt=1773153859604",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/PROJECTS.png?updatedAt=1773153859005",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/PROJECT_DETAIL2.png?updatedAt=1773153858856",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/default-1920x1080.png?updatedAt=1773153858619",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/ABOUT.png?updatedAt=1773153858600",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/default-1920x1080(2).png?updatedAt=1773153858121",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Portafolio%20V1/DETAIL_STACK.png?updatedAt=1773153858025",
    ],
    gitHuburl: "https://github.com/agueroda2004/Portfolio.git",
    liveSite: "https://daniel-aguero.vercel.app/",
    available: true,
    projectOverview: [
      "Portfolio v1 is a comprehensive digital showcase designed to consolidate and present my growing trajectory as a software engineering student. This project served as my primary professional interface, bridging the gap between my academic learning and my full-stack development capabilities through a collection of real-world applications.",
      "I took full ownership of the product lifecycle, from initial UI/UX conceptualization to final deployment. The platform was built with a focus on performance and clean code, ensuring a seamless cross-device experience that highlights my technical stack, including JavaScript, TypeScript, and various full-stack frameworks.",
    ],
    rolesResponsibilities: [
      "End-to-end Development",
      "Modular Code Architecture",
      "UI/UX Visual Design",
      "Responsive Layout System",
      "Deployment & Hosting",
    ],
    previusProject: {
      id: 2,
      name: "Librarian",
    },
    nextProject: {
      id: 4,
      name: "PostDestete",
    },
    technologies: ["React", "Tailwind", "JavaScript", "VS Code", "Git"],
  },
  {
    id: 4,
    name: "PostDestete",
    miniDescription: "Specialized agricultural management system for pig farms",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(2).png",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(5).png?updatedAt=1773154007053",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(4).png?updatedAt=1773154007027",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080.png?updatedAt=1773154007073",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(9).png?updatedAt=1773154007067",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(10).png?updatedAt=1773154007120",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(7).png?updatedAt=1773154007086",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(8).png?updatedAt=1773154007022",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(1).png?updatedAt=1773154006777",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/PostDestete/default-1920x1080(6).png?updatedAt=1773154006726",
    ],
    gitHuburl: "https://github.com/agueroda2004/Post-destete.git",
    liveSite: "Private app for a client",
    available: false,
    projectOverview: [
      "PostDestete is a specialized agricultural management system developed for a commercial pig farm to monitor and analyze pig mortality rates during the critical post-weaning stage. The platform transforms raw mortality data into actionable insights, providing a centralized tool for farm administrators to track animal health trends and optimize survival rates through data-driven decisions.",
      "The technical core of the system includes a comprehensive CRUD engine for managing disease catalogs and mortality logs, supported by a robust analytics dashboard. I engineered an advanced reporting module that generates real-time charts and metrics, all protected by a secure authentication layer to ensure the integrity of the farm's sensitive operational data.",
    ],
    rolesResponsibilities: [
      "Industrial System Design",
      "Data Visualization Dashboard",
      "Access Control Management",
      "Relational Database Design",
      "Reporting & Metrics Module",
    ],
    previusProject: {
      id: 3,
      name: "Portafolio v1",
    },
    nextProject: {
      id: 5,
      name: "Pokedex",
    },
    technologies: [
      "React",
      "Tailwind",
      "Neon",
      "TypeScript",
      "Vercel",
      "VS Code",
      "Git",
    ],
  },
  {
    id: 5,
    name: "Pokedex",
    miniDescription:
      "Data-driven app for searching and analyzing Pokémon stats",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(1).png?updatedAt=1773165102346",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(6).png?updatedAt=1773165102413",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(2).png?updatedAt=1773165102316",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(3).png?updatedAt=1773165102334",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(5).png?updatedAt=1773165102249",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080(7).png?updatedAt=1773165102113",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/default-1920x1080.png?updatedAt=1773165102141",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/iPhone-14-Pro-438x891(4).png?updatedAt=1773165102120",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/iPhone-14-Pro-438x891(3).png?updatedAt=1773165102082",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/iPhone-14-Pro-438x891.png?updatedAt=1773165102104",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Pokedex/iPhone-14-Pro-438x891(2).png?updatedAt=1773165101970",
    ],
    gitHuburl: "https://github.com/agueroda2004/Pokedex.git",
    liveSite: "https://pokedex-daniel-aguero.vercel.app/",
    available: true,
    projectOverview: [
      "Pokedex is a specialized data-driven application developed to solve the information gap for competitive and casual Pokémon players during gameplay. The platform serves as a high-performance reference tool, providing instant access to critical battle data, encounter logistics, and strategic insights that help players make informed decisions in real-time.",
      "The application leverages a comprehensive external API to fetch and display detailed Pokémon profiles, including type weaknesses, strengths, and full move-sets categorized by level and TM/HM availability. I focused on building a highly responsive and visual experience that integrates high-quality imagery with complex data structures, ensuring a seamless search and discovery flow.",
    ],
    rolesResponsibilities: [
      "External API Integration",
      "Complex Data Mapping",
      "Dynamic Content Rendering",
      "Search & Filter Logic",
      "Performance Optimization",
    ],
    previusProject: {
      id: 4,
      name: "PostDestete",
    },
    nextProject: {
      id: 6,
      name: "CoolStreet",
    },
    technologies: ["React", "Tailwind", "JavaScript", "VS Code", "Git"],
  },
  {
    id: 6,
    name: "CoolStreet",
    miniDescription: "Full-stack e-commerce platform for a streetwear brand",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img2.png?updatedAt=1773155906740",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img1.png?updatedAt=1773155907137",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img3.png?updatedAt=1773155906698",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img5.png?updatedAt=1773155906631",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img6.png?updatedAt=1773155906582",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/CoolStreet/Img4.png?updatedAt=1773155906553",
    ],
    gitHuburl: "Not available",
    liveSite: "Not available",
    available: false,
    projectOverview: [
      "CoolStreet is a comprehensive e-commerce platform developed for a specialized apparel retailer, focusing on delivering a seamless online shopping experience for high-quality shirts. The application manages the entire sales lifecycle, from product discovery through a dynamic catalog to secure checkout, providing the business with a professional and scalable digital storefront.",
      "The technical implementation features a full CRUD system for inventory management with cloud-hosted imagery, integrated shopping cart functionality, and an automated billing and invoicing module. To ensure global reach, I engineered a multi-language support system and a secure authentication layer, creating a robust environment for transaction processing and user data management.",
    ],
    rolesResponsibilities: [
      "E-commerce Architecture",
      "Inventory Admin Dashboard",
      "Multi-language (i18n) Support",
      "Automated Billing Workflow",
      "Conversion-focused UI",
    ],
    previusProject: {
      id: 5,
      name: "Pokedex",
    },
    nextProject: {
      id: 7,
      name: "NetFlix Clone",
    },

    technologies: [
      "Angular",
      "Tailwind",
      "Node",
      "TypeScript",
      "Git",
      "VS Code",
      "Express",
      "PostMan",
      "MySql",
    ],
  },
  {
    id: 7,
    name: "NetFlix Clone",
    miniDescription: "Streaming service interface with real-time movie trends",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Netflix%20Clone/Img2.png?updatedAt=1773155691145",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Netflix%20Clone/Img1.png?updatedAt=1773155691365",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Netflix%20Clone/Img3.png?updatedAt=1773155691015",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Netflix%20Clone/Img4.png?updatedAt=1773155690819",
    ],
    gitHuburl: "Not available",
    liveSite: "Not available",
    available: false,
    projectOverview: [
      "The Netflix Clone is a high-performance streaming interface developed as a technical challenge to replicate the seamless user experience of one of the world's most iconic digital platforms. The project focuses on real-time data synchronization and high-quality media delivery, providing a professional-grade environment for users to discover trending entertainment content.",
      "The technical architecture integrates secure user authentication with dynamic external API consumption to populate the storefront with current global trends. I implemented a detailed media view that connects directly with the YouTube API to fetch and play official trailers, ensuring an immersive and interactive browsing experience that mirrors industry standards.",
    ],
    rolesResponsibilities: [
      "RESTful API Integration",
      "YouTube Media Player",
      "Global State Management",
      "Private Route Security",
      "Lazy-loading Assets",
    ],
    previusProject: {
      id: 6,
      name: "CoolStreet",
    },
    nextProject: {
      id: 8,
      name: "Hotel Booking",
    },
    technologies: [
      "React",
      "Tailwind",
      "FireBase",
      "JavaScript",
      "Git",
      "VS Code",
    ],
  },
  {
    id: 8,
    name: "Hotel Booking",
    miniDescription:
      "Professional management and reservation platform for hotels",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Hotel%20Booking/Img3.png?updatedAt=1773155510440",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Hotel%20Booking/Img1.png?updatedAt=1773155510625",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Hotel%20Booking/Img4.png?updatedAt=1773155510313",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Hotel%20Booking/Img2.png?updatedAt=1773155509779",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Hotel%20Booking/Img5.png?updatedAt=1773155509014",
    ],
    gitHuburl: "Not available",
    liveSite: "Not available",
    available: false,
    projectOverview: [
      "Hotel Booking is a professional management and reservation platform designed to streamline operations for hospitality businesses. The system provides a comprehensive solution for room inventory management, allowing administrators to handle high volumes of data while offering a seamless booking experience for potential guests.",
      "The application features a robust administrative engine that includes a full CRUD system for room management and a sophisticated financial reporting module to track revenue and occupancy metrics. I engineered a real-time reservation system that manages availability and booking states, ensuring a reliable and efficient workflow from initial inquiry to final check-out.",
    ],
    rolesResponsibilities: [
      "Reservation Business Logic",
      "Financial Analytics Dashboard",
      "Admin CRUD Interface",
      "Data Integrity Validation",
      "Hospitality UX Design",
    ],
    previusProject: {
      id: 7,
      name: "NetFlix Clone",
    },
    nextProject: {
      id: 9,
      name: "Car Rental",
    },
    technologies: [
      "React",
      "Tailwind",
      "Node",
      "JavaScript",
      "Git",
      "VS Code",
      "Mongo",
      "PostMan",
      "Express",
    ],
  },
  {
    id: 9,
    name: "Car Rental",
    miniDescription: "Luxury vehicle management and reservation system",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img3.png?updatedAt=1773155288225",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img1.png?updatedAt=1773155288284",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img6.png?updatedAt=1773155288182",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img2.png?updatedAt=1773155288134",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img5.png?updatedAt=1773155287676",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Car%20Rental/Img4.png?updatedAt=1773155287624",
    ],
    gitHuburl: "Not available",
    liveSite: "Not available",
    available: false,
    projectOverview: [
      "Car Rental is a high-end luxury vehicle management and reservation system designed to provide a premium digital experience for car rental businesses. The platform offers a sophisticated interface for showcasing an elite fleet while automating the complex logistics of high-value rentals and customer management.",
      "The application integrates a robust authentication system with a specialized reservation engine and a full CRUD inventory module for vehicle management. To assist in business growth, I developed a comprehensive reporting suite that visualizes revenue streams and fleet performance, ensuring administrators have total control over their luxury assets and financial metrics.",
    ],
    rolesResponsibilities: [
      "Luxury Fleet Management",
      "Profitability Analytics",
      "Secure Booking System",
      "Scalable Inventory CRUD",
      "High-end UI/UX",
    ],
    previusProject: {
      id: 8,
      name: "Hotel Booking",
    },
    nextProject: {
      id: 10,
      name: "Taku-Dev",
    },
    technologies: [
      "React",
      "Tailwind",
      "Node",
      "JavaScript",
      "Git",
      "VS Code",
      "Mongo",
      "PostMan",
      "Express",
    ],
  },
  {
    id: 10,
    name: "Taku-Dev",
    miniDescription: "Official website for a custom software development firm",
    images: [
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(1).png?updatedAt=1773154468436",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080.png?updatedAt=1773154468227",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(9).png?updatedAt=1773154468198",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(5).png?updatedAt=1773154467921",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(7).png?updatedAt=1773154467910",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(3).png?updatedAt=1773154467873",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(2).png?updatedAt=1773154467815",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(6).png?updatedAt=1773154468300",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(4).png?updatedAt=1773154468257",
      "https://ik.imagekit.io/5zi86k8wt/portfolioV2/Taku-Dev/default-1920x1080(8).png?updatedAt=1773154467999",
    ],
    gitHuburl: "https://github.com/agueroda2004/taku-dev.git",
    liveSite: "https://www.taku-dev.com/",
    available: true,
    projectOverview: [
      "Taku-dev is a specialized software development firm founded to provide high-quality digital solutions for businesses across diverse industries, from retail to agriculture. The company focuses on bridging the gap between complex business challenges and scalable technological products, delivering custom-built applications that prioritize performance and user-centric design.",
      "As the lead developer and founder, I established the technical vision for the firm, overseeing the end-to-end development of multiple full-stack projects including e-commerce platforms and specialized management systems. Taku-dev serves as an umbrella for innovation, where I manage client requirements, technical architecture, and the deployment of robust software solutions using modern frameworks.",
    ],
    rolesResponsibilities: [
      "Lead Strategic Direction",
      "Custom Software Architect",
      "Infrastructure Design",
      "Client Requirement Management",
      "Quality Assurance Leadership",
    ],
    previusProject: {
      id: 9,
      name: "Car Rental",
    },
    nextProject: {
      id: 1,
      name: "Tenis Fresonas",
    },
    technologies: ["React", "Tailwind", "TypeScript", "Git", "VS Code"],
  },
];
